spring:
  application:
    name: gateway

server:
  port: ${PORT:5003}

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin #https://github.com/spring-cloud/spring-cloud-netflix/issues/1250
  routes:
    backend:
      path: /backend/**
      url: https://stswoon-fm-backend.herokuapp.com/
      sensitiveHeaders:
    authorization:
      path: /auth/**
      url: https://stswoon-fm-auth.herokuapp.com/auth/
      sensitiveHeaders: #https://piotrminkowski.wordpress.com/2017/02/22/microservices-security-with-oauth2/

eureka:
  client:
    enabled: false