# Spring properties
spring:
  application:
    name: back-service

# Discovery Server Access
eureka:
  instance:
      #leaseRenewalIntervalInSeconds: 10
      #securePortEnabled: true
      #metadataMap:
      #    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    #registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://localhost:5000/eureka/
      defaultZone: https://stswoon-fm-discovery.herokuapp.com/eureka
#  instance:
#    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

#ribbon.IsSecure: true

server:
  port: ${PORT:5001}
  #port: 5001

#management.security.enabled: false
