spring:
  application:
    name: backend

eureka:
  instance:
      #leaseRenewalIntervalInSeconds: 10
      #securePortEnabled: true
      #metadataMap:
      #    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    #registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: {$EUREKA:http://localhost:5000/eureka/}
#ribbon.IsSecure: true
#management.security.enabled: false

server:
  port: ${PORT:5001}

