spring:
  profiles:
    active:
      - local
#    include: common

---
spting:
  profile: common

spring:
  application:
    name: backend
  datasource:
    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

server:
  port: ${PORT:5001}

security:
  oauth2:
    client:
      client-id: oauth2_client
      client-secret: oauth2_client_secret
    resource:
      token-info-uri: http://localhost:5004/oauth/check_token


logging:
  level:
    ROOT: DEBUG
    nodomain.stswoon: DEBUG

createTestData: true
spring.jpa.show-sql: true

---
spting:
  profile: cloud

eureka:
  instance:
      #leaseRenewalIntervalInSeconds: 10
      #securePortEnabled: true
      #metadataMap:
      #    instanceId: ${spring.application.login}:${spring.application.instance_id:${server.port}}
  client:
    #registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA:http://localhost:5000/eureka/}
#ribbon.IsSecure: true
#management.security.enabled: false

---
spring:
  profile: local
#  include: common

spring.jpa.properties.hibernate.dialect: nodomain.stswoon.financemanager.backend.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto: create-drop
