spring:
  profiles:
    active: local

---
spring:
  profile: common

  application:
    name: backend
  datasource:
    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

server:
  port: ${PORT:5001}
  session:
    cookie:
      name: OAUTH2SESSION

auth-server: https://stswoon-fm-gateway.herokuapp.com/auth
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: oauth2_client
      client-secret: oauth2_client_secret
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
      authorized-grant-types: authorization_code,refresh_token,password,client_credentials,implicit
      authenticationScheme: header
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
      filter-order: 3 #https://stackoverflow.com/questions/43308625/spring-security-oauth2-always-redirects-to-login-page-having-a-valid-bearer-hea


createTestData: true
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create-drop #todo remove in production

---
spring:
  profile: cloud

---
spring:
  profile: test
  include:
    - common

  datasource.url: jdbc:sqlite:./target/localDb.db #todo bug all profiles are used
  jpa.properties.hibernate.dialect: com.enigmabridge.hibernate.dialect.SQLiteDialect

createTestData: false #because manual insert don't increase autoindex
disableOAuth2: true

---
spring:
  profile: local
  include:
    - common

  datasource.url: jdbc:sqlite:./backend/target/localDb.db
  jpa.properties.hibernate.dialect: com.enigmabridge.hibernate.dialect.SQLiteDialect

createTestData: true #todo bug all profiles are used
disableOAuth2: false #todo bug all profiles are used