# Spring properties
spring:
  application:
    name: backtst-service

# Discovery Server Access
eureka:
  instance:
      leaseRenewalIntervalInSeconds: 10
      #metadataMap:
      #    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://localhost:5000/eureka/
      defaultZone: https://stswoon-fm-discovery.herokuapp.com/eureka
#  instance:
#    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

server:
  port: ${PORT:5002}
  #port: 5001

management.security.enabled: false

